# Generated by Django 4.0.5 on 2022-09-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=120)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(default='Present', max_length=4, null=True)),
                ('school', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=100)),
                ('writeup', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('start_year', models.CharField(max_length=12)),
                ('end_year', models.CharField(default='Present', max_length=12, null=True)),
                ('experience_ul', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Websites', max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=200)),
                ('description_text', models.TextField(max_length=2000)),
                ('order', models.IntegerField(null=True)),
                ('icon_img', models.ImageField(blank=True, null=True, upload_to='service_icons/')),
                ('icon_class_bx', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField(blank=True, default='#', max_length=2000, null=True)),
                ('project_desc', models.TextField(max_length=5000, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=999)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('category', models.ForeignKey(default='Others', on_delete=django.db.models.deletion.CASCADE, to='resume.projectcategory')),
            ],
        ),
    ]
