# Generated by Django 4.0.5 on 2022-09-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_projectcategory_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_image1',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
