# Generated by Django 4.0.5 on 2022-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_project_image1_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(default='b2b-web-app'),
            preserve_default=False,
        ),
    ]
